### ISSUE TITLE
code

### ISSUE THREAD

**Issue by SeeU1119** [KU-CVLAB/INR-st#1]
Thanks for your excellent work. the results showed in paper are impressive, could you have any plan to release the code and pretrained weight.

**Comment by sunwoo76** [comment]
Thanks for your interest!
Sorry for delaying the codes.
The codes are going to be released this week :)

**Comment by sunwoo76** [comment]
> Thanks for your excellent work. the results showed in paper are impressive, could you have any plan to release the code and pretrained weight.

Sorry for the delaying in uploading the codes.
The codes are uploaded now.

Thanks :)
